// Shared In-Memory Database Store for InfraSync Phase 3
// Synchronized with PostgreSQL Prisma schema for resilient zero-downtime execution

export const dbStore = {
  users: [
    {
      id: 'demo-pm-uuid-001',
      name: 'Demo Project Manager',
      email: 'pm@infrasync.demo',
      role: 'PROJECT_MANAGER',
      createdAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'demo-se-uuid-002',
      name: 'Demo Site Engineer',
      email: 'se@infrasync.demo',
      role: 'SITE_ENGINEER',
      createdAt: '2026-01-02T00:00:00.000Z',
    },
    {
      id: 'demo-se-uuid-003',
      name: 'Priya Patel (Site Engineer)',
      email: 'se2@infrasync.demo',
      role: 'SITE_ENGINEER',
      createdAt: '2026-01-05T00:00:00.000Z',
    }
  ],

  projects: [
    {
      id: 'proj-001',
      name: 'Delhi Metro Expansion (Phase 4B)',
      location: 'Delhi NCR Corridor',
      description: '12.4 km elevated viaduct and 4 metro stations construction package.',
      startDate: '2026-01-01',
      endDate: '2026-12-30',
      status: 'ACTIVE',
      managerId: 'demo-pm-uuid-001',
      createdAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'proj-002',
      name: 'Western Dedicated Freight Corridor (Package 3)',
      location: 'Rewari - Vadodara Section',
      description: '48 km electrified double line freight railway corridor.',
      startDate: '2025-06-01',
      endDate: '2027-03-31',
      status: 'ACTIVE',
      managerId: 'demo-pm-uuid-001',
      createdAt: '2025-06-01T00:00:00.000Z',
    }
  ],

  projectMembers: [
    { id: 'pmem-001', projectId: 'proj-001', userId: 'demo-se-uuid-002', createdAt: '2026-01-03T00:00:00.000Z' },
    { id: 'pmem-002', projectId: 'proj-001', userId: 'demo-se-uuid-003', createdAt: '2026-01-06T00:00:00.000Z' },
    { id: 'pmem-003', projectId: 'proj-002', userId: 'demo-se-uuid-002', createdAt: '2026-01-10T00:00:00.000Z' },
  ],

  activities: [
    {
      id: 'act-001',
      projectId: 'proj-001',
      activityCode: 'CIV-001',
      name: 'Site Preparation & Utility Diversion',
      wbs: 'WBS-01.01',
      description: 'Clearing right-of-way and relocating high-voltage gas and power utilities.',
      plannedStart: '2026-01-01',
      plannedEnd: '2026-02-15',
      plannedQuantity: 100,
      actualQuantity: 100,
      unit: '%',
      status: 'COMPLETED',
      assignedToId: 'demo-se-uuid-002',
      createdAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'act-002',
      projectId: 'proj-001',
      activityCode: 'CIV-012',
      name: 'Geotechnical Bore Piling (1200mm dia)',
      wbs: 'WBS-01.02',
      description: 'Cast-in-situ reinforced piles for pier locations 01 through 32.',
      plannedStart: '2026-02-01',
      plannedEnd: '2026-04-30',
      plannedQuantity: 450,
      actualQuantity: 450,
      unit: 'm',
      status: 'COMPLETED',
      assignedToId: 'demo-se-uuid-002',
      createdAt: '2026-02-01T00:00:00.000Z',
    },
    {
      id: 'act-003',
      projectId: 'proj-001',
      activityCode: 'CIV-023',
      name: 'Foundation Construction',
      wbs: 'WBS-01.03',
      description: 'Reinforced concrete foundation casting for Pier Cap 14 to 18 in Zone A.',
      plannedStart: '2026-05-01',
      plannedEnd: '2026-07-15',
      plannedQuantity: 80,
      actualQuantity: 65,
      unit: 'm³',
      status: 'DELAYED',
      assignedToId: 'demo-se-uuid-002',
      createdAt: '2026-05-01T00:00:00.000Z',
    },
    {
      id: 'act-004',
      projectId: 'proj-001',
      activityCode: 'CIV-034',
      name: 'Pier Shaft & Pier Cap Casting',
      wbs: 'WBS-01.04',
      description: 'Slipform shuttering and concrete pouring for elevated piers.',
      plannedStart: '2026-06-01',
      plannedEnd: '2026-09-30',
      plannedQuantity: 36,
      actualQuantity: 24,
      unit: 'piers',
      status: 'IN_PROGRESS',
      assignedToId: 'demo-se-uuid-002',
      createdAt: '2026-06-01T00:00:00.000Z',
    },
    {
      id: 'act-005',
      projectId: 'proj-001',
      activityCode: 'CIV-045',
      name: 'Pre-cast Box Girder Launching',
      wbs: 'WBS-01.05',
      description: 'Erection and tensioning of segmental superstructure spans.',
      plannedStart: '2026-07-01',
      plannedEnd: '2026-11-30',
      plannedQuantity: 28,
      actualQuantity: 14,
      unit: 'spans',
      status: 'IN_PROGRESS',
      assignedToId: 'demo-se-uuid-002',
      createdAt: '2026-07-01T00:00:00.000Z',
    },
    {
      id: 'act-006',
      projectId: 'proj-001',
      activityCode: 'TRK-001',
      name: 'Ballastless Track Slab Concreting',
      wbs: 'WBS-02.01',
      description: 'High-precision plinth track slab construction for up/down mainline tracks.',
      plannedStart: '2026-08-01',
      plannedEnd: '2026-11-15',
      plannedQuantity: 12000,
      actualQuantity: 4200,
      unit: 'm',
      status: 'IN_PROGRESS',
      assignedToId: 'demo-se-uuid-003',
      createdAt: '2026-08-01T00:00:00.000Z',
    },
    {
      id: 'act-007',
      projectId: 'proj-001',
      activityCode: 'ELE-011',
      name: '25kV OHE Overhead Traction Installation',
      wbs: 'WBS-02.02',
      description: 'Catenary and contact wire stringing across viaduct section.',
      plannedStart: '2026-09-01',
      plannedEnd: '2026-12-10',
      plannedQuantity: 24,
      actualQuantity: 5,
      unit: 'km',
      status: 'IN_PROGRESS',
      assignedToId: 'demo-se-uuid-003',
      createdAt: '2026-09-01T00:00:00.000Z',
    },
    {
      id: 'act-008',
      projectId: 'proj-001',
      activityCode: 'SIG-002',
      name: 'CBTC Signaling & Train Control Cabling',
      wbs: 'WBS-02.03',
      description: 'Wayside fiber optic and beacon installation for automatic train operation.',
      plannedStart: '2026-10-01',
      plannedEnd: '2026-12-25',
      plannedQuantity: 18,
      actualQuantity: 0,
      unit: 'km',
      status: 'NOT_STARTED',
      assignedToId: 'demo-se-uuid-003',
      createdAt: '2026-10-01T00:00:00.000Z',
    },
    {
      id: 'act-009',
      projectId: 'proj-001',
      activityCode: 'STA-005',
      name: 'Station Finishes & Platform Screen Doors',
      wbs: 'WBS-03.01',
      description: 'Architectural cladding, false ceilings, and PSD safety barriers.',
      plannedStart: '2026-08-15',
      plannedEnd: '2026-12-20',
      plannedQuantity: 4,
      actualQuantity: 1,
      unit: 'stations',
      status: 'IN_PROGRESS',
      assignedToId: 'demo-se-uuid-002',
      createdAt: '2026-08-15T00:00:00.000Z',
    },
    {
      id: 'act-010',
      projectId: 'proj-002',
      activityCode: 'MEP-008',
      name: 'HVAC & Auxiliary Substation Installation',
      wbs: 'WBS-03.02',
      description: '33/11kV auxiliary transformer and ventilation ducting.',
      plannedStart: '2026-09-01',
      plannedEnd: '2026-12-15',
      plannedQuantity: 100,
      actualQuantity: 20,
      unit: '%',
      status: 'IN_PROGRESS',
      assignedToId: 'demo-se-uuid-003',
      createdAt: '2026-09-01T00:00:00.000Z',
    }
  ],

  risks: [
    {
      id: 'risk-001',
      activityId: 'act-003',
      activityName: 'Foundation Construction',
      activityCode: 'CIV-023',
      riskLevel: 'HIGH',
      probability: 0.85,
      estimatedDelay: '4 Days',
      cause: 'Ready-mix concrete delivery logistical bottlenecks and monsoon water-table surge.',
      recommendation: 'Prioritize material delivery, mobilize secondary batching plant, and increase manpower.',
      createdAt: '2026-05-10T00:00:00.000Z',
    },
    {
      id: 'risk-002',
      activityId: 'act-005',
      activityName: 'Pre-cast Box Girder Launching',
      activityCode: 'CIV-045',
      riskLevel: 'MEDIUM',
      probability: 0.60,
      estimatedDelay: '3 Days',
      cause: 'High wind gusts delaying heavy segment erection gantry clearance.',
      recommendation: 'Schedule segment lifts during morning low-wind window and add stabilization guy-wires.',
      createdAt: '2026-07-05T00:00:00.000Z',
    },
    {
      id: 'risk-003',
      activityId: 'act-006',
      activityName: 'Ballastless Track Slab Concreting',
      activityCode: 'TRK-001',
      riskLevel: 'LOW',
      probability: 0.35,
      estimatedDelay: '1 Day',
      cause: 'Delayed delivery of shear connector reinforcement cages.',
      recommendation: 'Mobilize buffer inventory from Central Yard B.',
      createdAt: '2026-08-12T00:00:00.000Z',
    }
  ],

  progressUpdates: [
    {
      id: 'prog-001',
      activityId: 'act-003',
      submittedById: 'demo-se-uuid-002',
      actualQuantity: 65,
      actualPercentage: 81.25,
      remarks: 'Casting completed for Pier 14 & 15. Pier 16 awaiting rebar inspection clearance.',
      status: 'PENDING',
      reviewRemarks: null,
      reviewedAt: null,
      reviewedById: null,
      createdAt: '2026-09-09T18:00:00.000Z',
    },
    {
      id: 'prog-002',
      activityId: 'act-006',
      submittedById: 'demo-se-uuid-003',
      actualQuantity: 4200,
      actualPercentage: 35.0,
      remarks: 'Track slab plinth concreting finished between Ch 14+200 and 18+400.',
      status: 'PENDING',
      reviewRemarks: null,
      reviewedAt: null,
      reviewedById: null,
      createdAt: '2026-09-09T16:30:00.000Z',
    },
    {
      id: 'prog-003',
      activityId: 'act-002',
      submittedById: 'demo-se-uuid-002',
      actualQuantity: 450,
      actualPercentage: 100.0,
      remarks: 'Bored piling test loads verified by third-party geotechnical lab.',
      status: 'APPROVED',
      reviewRemarks: 'Quality test certificates validated. Approved for invoicing.',
      reviewedAt: '2026-05-02T10:00:00.000Z',
      reviewedById: 'demo-pm-uuid-001',
      createdAt: '2026-05-01T15:00:00.000Z',
    },
    {
      id: 'prog-004',
      activityId: 'act-004',
      submittedById: 'demo-se-uuid-002',
      actualQuantity: 28,
      actualPercentage: 77.7,
      remarks: 'Pier cap pour completed for pier 28.',
      status: 'REJECTED',
      reviewRemarks: 'Cube compression test reports for batch #C4 missing. Please resubmit with lab test sheets.',
      reviewedAt: '2026-07-10T14:30:00.000Z',
      reviewedById: 'demo-pm-uuid-001',
      createdAt: '2026-07-09T17:00:00.000Z',
    }
  ],

  siteEvidences: [
    {
      id: 'evid-001',
      activityId: 'act-003',
      uploadedById: 'demo-se-uuid-002',
      fileUrl: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=800&q=80',
      fileName: 'pier15-footing-concrete.jpg',
      fileType: 'image/jpeg',
      evidenceType: 'PHOTO',
      capturedDate: '2026-09-09T14:00:00.000Z',
      description: 'Foundation concrete pour in progress for Pier 15 footings with batching truck #08.',
      aiStatus: 'COMPLETED',
      aiConfidence: 88,
      aiExtractedActivity: 'Foundation Construction',
      aiExtractedLocation: 'Zone A - Pier 14/15',
      aiExtractedQuantity: null,
      aiExtractedUnit: 'm3',
      aiExtractedProgress: 80.0,
      aiExtractedStatus: 'IN_PROGRESS',
      aiIssues: JSON.stringify(['Slight water accumulation in footing trench']),
      aiRemarks: 'Reinforced concrete foundation casting visible for Pier 15 footings with transit mixer on site.',
      aiMaterials: JSON.stringify(['Reinforcement steel rebar TMT 500D', 'Concrete M35 grade']),
      aiManpower: '1 Foreman, 6 Bar-benders, 4 Concreting masons',
      aiEquipment: 'Transit Mixer #08, Concrete Boom Pump',
      reviewStatus: 'CONFIRMED',
      reviewedById: 'demo-se-uuid-002',
      reviewedAt: '2026-09-09T14:30:00.000Z',
      createdAt: '2026-09-09T14:15:00.000Z',
      updatedAt: '2026-09-09T14:30:00.000Z',
    },
    {
      id: 'evid-002',
      activityId: 'act-003',
      uploadedById: 'demo-se-uuid-002',
      fileUrl: '/docs/dpr-delhi-metro-sep09.pdf',
      fileName: 'DPR_Delhi_Metro_Phase4B_09Sep2026.pdf',
      fileType: 'application/pdf',
      evidenceType: 'DPR',
      capturedDate: '2026-09-09T17:30:00.000Z',
      description: 'Daily Progress Report - Package 4B, Zone A foundation casting shift summary.',
      aiStatus: 'COMPLETED',
      aiConfidence: 94,
      aiExtractedActivity: 'Foundation Construction',
      aiExtractedLocation: 'Zone A',
      aiExtractedQuantity: 65.0,
      aiExtractedUnit: 'm3',
      aiExtractedProgress: 81.0,
      aiExtractedStatus: 'IN_PROGRESS',
      aiIssues: JSON.stringify(['Reinforcement material shortage']),
      aiRemarks: 'Foundation work at Zone A completed up to 65 cubic meters. Progress slightly constrained by rebar dispatch delay.',
      aiMaterials: JSON.stringify(['Reinforcement steel TMT', 'Ready-Mix Concrete M35']),
      aiManpower: '1 Site Supervisor, 8 Steel Fixers, 5 Laborers',
      aiEquipment: 'Transit Mixer (Batching Truck #08), Tower Crane 1',
      reviewStatus: 'CONFIRMED',
      reviewedById: 'demo-se-uuid-002',
      reviewedAt: '2026-09-09T18:00:00.000Z',
      createdAt: '2026-09-09T17:45:00.000Z',
      updatedAt: '2026-09-09T18:00:00.000Z',
    },
    {
      id: 'evid-003',
      activityId: 'act-005',
      uploadedById: 'demo-se-uuid-002',
      fileUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
      fileName: 'girder-launching-span18.jpg',
      fileType: 'image/jpeg',
      evidenceType: 'PHOTO',
      capturedDate: '2026-09-08T11:20:00.000Z',
      description: 'Segmental box girder span erection using mobile launching truss.',
      aiStatus: 'COMPLETED',
      aiConfidence: 89,
      aiExtractedActivity: 'Pre-cast Box Girder Launching',
      aiExtractedLocation: 'Viaduct Span 18-19',
      aiExtractedQuantity: null,
      aiExtractedUnit: 'span',
      aiExtractedProgress: 60.0,
      aiExtractedStatus: 'IN_PROGRESS',
      aiIssues: JSON.stringify(['High wind velocity monitored before final segment stitch']),
      aiRemarks: 'Segmental erection gantry loaded with precast concrete segments.',
      aiMaterials: JSON.stringify(['Prestressed concrete box segments', 'High tensile strands']),
      aiManpower: '1 Erection Engineer, 12 Specialized rigging crew',
      aiEquipment: 'Launching Gantry 120T, Multi-axle hydraulic transporter',
      reviewStatus: 'PENDING_REVIEW',
      reviewedById: null,
      reviewedAt: null,
      createdAt: '2026-09-08T12:00:00.000Z',
      updatedAt: '2026-09-08T12:00:00.000Z',
    }
  ]
};
